window.CARS = [
  {
    "id": 1,
    "slug": "audi-s3-sportback",
    "name": "Audi S3 Sportback",
    "year": 2018,
    "km": 190000,
    "transmission": "Automatik",
    "fuel": "Benzin",
    "price": 38000,
    "sold": false,
    "headImage": "images/cars/audi-s3-sportback/6.jpg",
    "images": [
      "images/cars/audi-s3-sportback/1.jpg",
      "images/cars/audi-s3-sportback/2.jpg",
      "images/cars/audi-s3-sportback/3.jpg",
      "images/cars/audi-s3-sportback/4.jpg",
      "images/cars/audi-s3-sportback/5.jpg",
      "images/cars/audi-s3-sportback/7.jpg",
      "images/cars/audi-s3-sportback/8.jpg",
      "images/cars/audi-s3-sportback/9.jpg",
      "images/cars/audi-s3-sportback/10.jpg",
      "images/cars/audi-s3-sportback/11.jpg",
      "images/cars/audi-s3-sportback/12.jpg",
      "images/cars/audi-s3-sportback/13.jpg"
    ],
    "description": "Poslednji 8V model. Auto u fabričkom stanju, najveći mogući stepen opreme. Redovno održavan, kompletno servisiran, nove disk pločice. Online Audi servisna istorija. Registrovan, kupljen u Švajcarskoj. Prva registracija 2019. Garancija na sve podatke, ispravnost i regularnost.",
    "specs": {
      "engine": "2.0 TFSI",
      "power": "310 KS / 228 kW",
      "displacement": "1984 ccm",
      "drive": "Quattro (AWD)",
      "body": "Hatchback",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "S tronic — 5 modova vožnje",
      "Virtuelna tabla",
      "Matrix farovi i full LED stopovi",
      "Bang & Olufsen sistem ozvučenja",
      "Panorama krov",
      "Original Rotor 19\" felne",
      "Kožna sjedišta sa grijanjem i masažom",
      "F1 šaltanje na volanu",
      "Parking senzori 360°",
      "Rikverc kamera",
      "Senzori za svjetla i kišu",
      "Automatska duga svjetla",
      "Lane assist, samokočenje, autohold",
      "Adaptivni tempomat",
      "AC digitalna klima 3 zone",
      "CarPlay i prikaz G sile / snage motora",
      "Paljenje na dugme i keyless",
      "Start/stop sistem",
      "Automatsko sklapanje retrovizora",
      "Ambient light"
    ]
  },
  {
    "id": 2,
    "slug": "audi-sq5-black-edition",
    "name": "Audi SQ5 Black Edition",
    "year": 2014,
    "km": 213000,
    "transmission": "Automatik",
    "fuel": "Dizel",
    "price": 26500,
    "sold": false,
    "headImage": "images/cars/audi-sq5-black-edition/6.jpg",
    "images": [
      "images/cars/audi-sq5-black-edition/1.jpg",
      "images/cars/audi-sq5-black-edition/2.jpg",
      "images/cars/audi-sq5-black-edition/3.jpg",
      "images/cars/audi-sq5-black-edition/4.jpg",
      "images/cars/audi-sq5-black-edition/5.jpg",
      "images/cars/audi-sq5-black-edition/7.jpg",
      "images/cars/audi-sq5-black-edition/8.jpg",
      "images/cars/audi-sq5-black-edition/9.jpg",
      "images/cars/audi-sq5-black-edition/10.jpg",
      "images/cars/audi-sq5-black-edition/11.jpg",
      "images/cars/audi-sq5-black-edition/12.jpg",
      "images/cars/audi-sq5-black-edition/13.jpg",
      "images/cars/audi-sq5-black-edition/14.jpg",
      "images/cars/audi-sq5-black-edition/15.jpg",
      "images/cars/audi-sq5-black-edition/16.jpg",
      "images/cars/audi-sq5-black-edition/17.jpg",
      "images/cars/audi-sq5-black-edition/18.jpg",
      "images/cars/audi-sq5-black-edition/19.jpg",
      "images/cars/audi-sq5-black-edition/20.jpg"
    ],
    "description": "Auto u odličnom stanju, izuzetno očuvan. Najveći stepen opreme — Black Edition paket. Original 20\" felne. Odrađeni svi servisi, kompletan servis trapova. Registrovan do 3/2027. Servisna istorija dostupna, pisana garancija na ispravnost dijelova automobila i servise.",
    "specs": {
      "engine": "3.0 V6 BiTDI",
      "power": "313 KS / 230 kW",
      "displacement": "2967 ccm",
      "drive": "Quattro (AWD)",
      "body": "SUV",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "5 modova vožnje",
      "Dupli panorama krov",
      "F1 šaltanje na volanu",
      "Alcantara/koža električna sjedišta",
      "Grijanje sjedišta i stakala",
      "AC digitalna klima",
      "Offroad mode vožnje",
      "ACC, praćenje traka, samokočenje",
      "Rikverc kamera, parking senzori",
      "Automatska svjetla, svjetla za maglu",
      "Senzori za svjetla i kišu",
      "Električni gepek",
      "Start/stop sistem",
      "Navigacija / multimedija"
    ]
  },
  {
    "id": 12,
    "slug": "citroen-c3",
    "name": "Citroën C3 1.6 e-HDi Exclusive",
    "year": 2013,
    "km": 236000,
    "transmission": "Manuelni",
    "fuel": "Dizel",
    "price": 5600,
    "sold": false,
    "badge": "NOVO",
    "headImage": "images/cars/citroen-c3/1.jpg",
    "images": [
      "images/cars/citroen-c3/2.jpg",
      "images/cars/citroen-c3/3.jpg",
      "images/cars/citroen-c3/4.jpg",
      "images/cars/citroen-c3/5.jpg",
      "images/cars/citroen-c3/6.jpg",
      "images/cars/citroen-c3/7.jpg",
      "images/cars/citroen-c3/8.jpg",
      "images/cars/citroen-c3/9.jpg",
      "images/cars/citroen-c3/10.jpg",
      "images/cars/citroen-c3/11.jpg",
      "images/cars/citroen-c3/12.jpg"
    ],
    "description": "Auto u izvanrednom stanju. Fabrička boja, Exclusive oprema. Tek odrađen servis, gume kao nove, 2 ključa. Kupljen od prvog vlasnika. Posjeduje servisnu dokumentaciju, CarVertical izvještaj i RDW. Ocarinjen, na ime kupca.",
    "specs": {
      "engine": "1.6 e-HDi",
      "power": "92 KS / 68 kW",
      "displacement": "1560 ccm",
      "drive": "Prednji (FWD)",
      "body": "Hatchback",
      "color": "Siva metalik",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "Navigacija / multimedija",
      "AC digitalna klima",
      "Parking senzori",
      "LED svjetla",
      "Svjetla za maglu",
      "Automatska svjetla",
      "Senzori za svjetla i kišu",
      "Tempomat / putni računar",
      "Start/stop sistem",
      "ESP sistem",
      "Sva 4 električna podizača",
      "Električno sklapanje retrovizora",
      "Podesiva sjedišta",
      "Posebna metalik boja",
      "Posebni poklopci retrovizora",
      "Hrom paket"
    ]
  },
  {
    "id": 11,
    "slug": "audi-a3-sportback",
    "name": "Audi A3 Sportback 2.0 TDI Quattro",
    "year": 2011,
    "km": 238000,
    "transmission": "Manuelni",
    "fuel": "Dizel",
    "price": 8900,
    "sold": true,
    "badge": "NOVO",
    "headImage": "images/cars/audi-a3-sportback/2.jpg",
    "images": [
      "images/cars/audi-a3-sportback/1.jpg",
      "images/cars/audi-a3-sportback/3.jpg",
      "images/cars/audi-a3-sportback/4.jpg",
      "images/cars/audi-a3-sportback/5.jpg",
      "images/cars/audi-a3-sportback/6.jpg",
      "images/cars/audi-a3-sportback/7.jpg",
      "images/cars/audi-a3-sportback/8.jpg",
      "images/cars/audi-a3-sportback/9.jpg",
      "images/cars/audi-a3-sportback/10.jpg",
      "images/cars/audi-a3-sportback/11.jpg",
      "images/cars/audi-a3-sportback/12.jpg",
      "images/cars/audi-a3-sportback/13.jpg",
      "images/cars/audi-a3-sportback/14.jpg",
      "images/cars/audi-a3-sportback/15.jpg",
      "images/cars/audi-a3-sportback/16.jpg"
    ],
    "description": "Auto u vrhunskom stanju. Maksimalno očuvan, visok stepen dodatne opreme. Kompletno servisiran (veliki servis, mali servis, novi set kvačila), 4 gume all season kao nove. Posjeduje račune servisa i 2 originalna ključa. Ocarinjen, na ime kupca. Cijena 8900 € po dogovoru.",
    "specs": {
      "engine": "2.0 TDI",
      "power": "140 KS / 103 kW",
      "displacement": "1968 ccm",
      "drive": "Quattro (AWD)",
      "body": "Hatchback",
      "color": "Crna",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "Multifunkcionalni volan sa komandama",
      "Kožna sjedišta sa grijanjem",
      "Dupla panorama krov",
      "Original Audi multimedija / navigacija",
      "AC digitalna klima 2 zone",
      "Start/stop sistem",
      "ESP sistem",
      "Original Audi felne",
      "Svjetla za maglu",
      "Grijanje retrovizora",
      "Električni podizači"
    ]
  },
  {
    "id": 10,
    "slug": "renault-megane",
    "name": "Renault Mégane 1.5 dCi",
    "year": 2014,
    "km": 231000,
    "transmission": "Manuelni",
    "fuel": "Dizel",
    "price": 6700,
    "sold": true,
    "badge": "NOVO",
    "headImage": "images/cars/renault-megane/1.jpg",
    "images": [
      "images/cars/renault-megane/2.jpg",
      "images/cars/renault-megane/3.jpg",
      "images/cars/renault-megane/4.jpg",
      "images/cars/renault-megane/5.jpg",
      "images/cars/renault-megane/6.jpg",
      "images/cars/renault-megane/7.jpg",
      "images/cars/renault-megane/8.jpg",
      "images/cars/renault-megane/9.jpg",
      "images/cars/renault-megane/10.jpg",
      "images/cars/renault-megane/11.jpg",
      "images/cars/renault-megane/12.jpg",
      "images/cars/renault-megane/13.jpg",
      "images/cars/renault-megane/14.jpg",
      "images/cars/renault-megane/15.jpg",
      "images/cars/renault-megane/16.jpg"
    ],
    "description": "Renault Mégane 1.5 dCi 70 kW, 6 brzina, godište 2014, kilometraža 231.000 km. Auto u odličnom stanju, izuzetno očuvan, visok stepen opreme. Tek odrađen servis, kupljen od prvog vlasnika, nove gume, 2 ključa. Ocarinjen, na ime kupca. Servisna istorija dostupna, garancija na kilometražu i godinu proizvodnje!",
    "specs": {
      "engine": "1.5 dCi",
      "power": "95 KS / 70 kW",
      "displacement": "1461 ccm",
      "drive": "Prednji (FWD)",
      "body": "Hatchback",
      "color": "Perla bijela",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "Navigacija / multimedija",
      "Bi-Xenon LED farovi",
      "Parking senzori",
      "Svjetla za maglu",
      "Senzori za svjetla i kišu",
      "ISOFIX sjedišta",
      "Multifunkcionalni volan sa komandama",
      "Električno sklapanje retrovizora",
      "Digitalna (AC) klima",
      "Originalne aluminijske felne",
      "Grijanje stakala",
      "Start/Stop sistem",
      "Paljenje na dugme"
    ]
  },
  {
    "id": 3,
    "slug": "ford-fiesta-titanium",
    "name": "Ford Fiesta Titanium",
    "year": 2013,
    "km": 224000,
    "transmission": "Manuelni",
    "fuel": "Dizel",
    "price": 5900,
    "sold": true,
    "headImage": "images/cars/ford-fiesta-titanium/1.jpg",
    "images": [
      "images/cars/ford-fiesta-titanium/2.jpg",
      "images/cars/ford-fiesta-titanium/3.jpg",
      "images/cars/ford-fiesta-titanium/4.jpg",
      "images/cars/ford-fiesta-titanium/5.jpg",
      "images/cars/ford-fiesta-titanium/6.jpg",
      "images/cars/ford-fiesta-titanium/7.jpg",
      "images/cars/ford-fiesta-titanium/8.jpg",
      "images/cars/ford-fiesta-titanium/9.jpg",
      "images/cars/ford-fiesta-titanium/10.jpg",
      "images/cars/ford-fiesta-titanium/11.jpg",
      "images/cars/ford-fiesta-titanium/12.jpg",
      "images/cars/ford-fiesta-titanium/13.jpg",
      "images/cars/ford-fiesta-titanium/14.jpg",
      "images/cars/ford-fiesta-titanium/15.jpg",
      "images/cars/ford-fiesta-titanium/16.jpg"
    ],
    "description": "Auto u odličnom stanju, najveći stepen opreme Titanium. Urađen mali servis, nove gume, 2 ključa. Ocarinjen, na ime kupca.",
    "specs": {
      "engine": "1.6 TDCi",
      "power": "95 KS / 70 kW",
      "displacement": "1560 ccm",
      "drive": "Prednji (FWD)",
      "body": "Hatchback",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "Parking senzori",
      "Komande na volanu",
      "Isofix sjedišta",
      "AC digitalna klima",
      "Navigacija / multimedija",
      "Keyless off",
      "Start/stop sistem",
      "Automatska svjetla",
      "Senzori za svjetla i kišu",
      "Aluminijske felne",
      "Ambient light",
      "Sva 4 električna podizača",
      "Tempomat"
    ]
  },
  {
    "id": 4,
    "slug": "s5-look",
    "name": "Audi A5 S line Sportback (S5 Look)",
    "year": 2017,
    "km": 77000,
    "transmission": "Automatik",
    "fuel": "Dizel",
    "price": null,
    "sold": true,
    "headImage": "images/cars/s5-look/1.jpg",
    "images": [
      "images/cars/s5-look/2.jpg",
      "images/cars/s5-look/3.jpg"
    ],
    "description": "Audi A5 Sportback u S5 look paketu. 2.0 TDI 140 kW, godište 2017, kilometraža 77.000 km.",
    "specs": {
      "engine": "2.0 TDI",
      "power": "190 KS / 140 kW",
      "displacement": "1968 ccm",
      "drive": "—",
      "body": "Hatchback",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": []
  },
  {
    "id": 5,
    "slug": "cayen",
    "name": "Porsche Cayenne GTS Look",
    "year": 2012,
    "km": 177000,
    "transmission": "Automatik",
    "fuel": "Dizel",
    "price": null,
    "sold": true,
    "headImage": "images/cars/cayen/1.jpg",
    "images": [
      "images/cars/cayen/2.jpg",
      "images/cars/cayen/3.jpg",
      "images/cars/cayen/4.jpg"
    ],
    "description": "Porsche Cayenne u GTS look paketu. 3.0 TDI 180 kW, godište 2012, kilometraža 177.000 km.",
    "specs": {
      "engine": "3.0 TDI",
      "power": "245 KS / 180 kW",
      "displacement": "2967 ccm",
      "drive": "AWD",
      "body": "SUV",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": []
  },
  {
    "id": 6,
    "slug": "7R",
    "name": "VW Golf 7R 400",
    "year": 2013,
    "km": 190000,
    "transmission": "Automatik",
    "fuel": "Benzin",
    "price": null,
    "sold": true,
    "headImage": "images/cars/7R/1.jpg",
    "images": [
      "images/cars/7R/2.jpg",
      "images/cars/7R/3.jpg",
      "images/cars/7R/4.jpg",
      "images/cars/7R/5.jpg",
      "images/cars/7R/6.jpg"
    ],
    "description": "VW Golf 7R sa ~400 KS. 2.0 TSI 296 kW, godište 2013, kilometraža 190.000 km.",
    "specs": {
      "engine": "2.0 TSI",
      "power": "400 KS / 296 kW",
      "displacement": "1984 ccm",
      "drive": "4Motion (AWD)",
      "body": "Hatchback",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": []
  },
  {
    "id": 7,
    "slug": "g30",
    "name": "BMW G30 520d SportLine",
    "year": 2017,
    "km": 235000,
    "transmission": "Automatik",
    "fuel": "Dizel",
    "price": null,
    "sold": true,
    "headImage": "images/cars/g30/4.jpg",
    "images": [
      "images/cars/g30/1.jpg",
      "images/cars/g30/2.jpg",
      "images/cars/g30/3.jpg",
      "images/cars/g30/5.jpg"
    ],
    "description": "BMW G30 520d SportLine. 2.0 dizel 140 kW, godište 2017, kilometraža 235.000 km.",
    "specs": {
      "engine": "2.0d",
      "power": "190 KS / 140 kW",
      "displacement": "1995 ccm",
      "drive": "Zadnji (RWD)",
      "body": "Limuzina",
      "color": "—",
      "doors": 4,
      "seats": 5
    },
    "features": []
  },
  {
    "id": 8,
    "slug": "125d",
    "name": "BMW 125d M Sport",
    "year": 2014,
    "km": 240000,
    "transmission": "Automatik",
    "fuel": "Dizel",
    "price": null,
    "sold": true,
    "headImage": "images/cars/125d/2.jpg",
    "images": [
      "images/cars/125d/1.jpg",
      "images/cars/125d/3.jpg",
      "images/cars/125d/4.jpg"
    ],
    "description": "BMW 125d M Sport, full M Sport paket. 2.0 TwinPowerTurbo 160 kW, godište 2014, kilometraža 240.000 km.",
    "specs": {
      "engine": "2.0 TwinPowerTurbo",
      "power": "218 KS / 160 kW",
      "displacement": "1995 ccm",
      "drive": "Zadnji (RWD)",
      "body": "Hatchback",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "Full M Sport paket"
    ]
  },
  {
    "id": 9,
    "slug": "7GTD",
    "name": "VW Golf 7.5 GTD",
    "year": 2018,
    "km": 168000,
    "transmission": "Automatik",
    "fuel": "Dizel",
    "price": null,
    "sold": true,
    "headImage": "images/cars/7GTD/1.jpg",
    "images": [
      "images/cars/7GTD/2.jpg",
      "images/cars/7GTD/3.jpg",
      "images/cars/7GTD/4.jpg",
      "images/cars/7GTD/5.jpg"
    ],
    "description": "VW Golf 7.5 GTD sa DSG mjenjačem. 2.0 TDI 135 kW, godište 2018, kilometraža 168.000 km.",
    "specs": {
      "engine": "2.0 TDI",
      "power": "184 KS / 135 kW",
      "displacement": "1968 ccm",
      "drive": "Prednji (FWD)",
      "body": "Hatchback",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "DSG mjenjač"
    ]
  }
];
