window.CARS = [
  {
    "id": 1,
    "slug": "audi-s3-sportback",
    "name": "Audi S3 Sportback",
    "year": 2018,
    "km": 190000,
    "transmission": "Automatik",
    "fuel": "Benzin",
    "price": 38000,
    "sold": false,
    "headImage": "images/cars/audi-s3-sportback/6.jpg",
    "images": [
      "images/cars/audi-s3-sportback/1.jpg",
      "images/cars/audi-s3-sportback/2.jpg",
      "images/cars/audi-s3-sportback/3.jpg",
      "images/cars/audi-s3-sportback/4.jpg",
      "images/cars/audi-s3-sportback/5.jpg",
      "images/cars/audi-s3-sportback/7.jpg",
      "images/cars/audi-s3-sportback/8.jpg",
      "images/cars/audi-s3-sportback/9.jpg",
      "images/cars/audi-s3-sportback/10.jpg",
      "images/cars/audi-s3-sportback/11.jpg",
      "images/cars/audi-s3-sportback/12.jpg",
      "images/cars/audi-s3-sportback/13.jpg"
    ],
    "description": "Poslednji 8V model. Auto u fabričkom stanju, najveći mogući stepen opreme. Redovno održavan, kompletno servisiran, nove disk pločice. Online Audi servisna istorija. Registrovan, kupljen u Švajcarskoj. Prva registracija 2019. Garancija na sve podatke, ispravnost i regularnost.",
    "specs": {
      "engine": "2.0 TFSI",
      "power": "310 KS / 228 kW",
      "displacement": "1984 ccm",
      "drive": "Quattro (AWD)",
      "body": "Hatchback",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "S tronic — 5 modova vožnje",
      "Virtuelna tabla",
      "Matrix farovi i full LED stopovi",
      "Bang & Olufsen sistem ozvučenja",
      "Panorama krov",
      "Original Rotor 19\" felne",
      "Kožna sjedišta sa grijanjem i masažom",
      "F1 šaltanje na volanu",
      "Parking senzori 360°",
      "Rikverc kamera",
      "Senzori za svjetla i kišu",
      "Automatska duga svjetla",
      "Lane assist, samokočenje, autohold",
      "Adaptivni tempomat",
      "AC digitalna klima 3 zone",
      "CarPlay i prikaz G sile / snage motora",
      "Paljenje na dugme i keyless",
      "Start/stop sistem",
      "Automatsko sklapanje retrovizora",
      "Ambient light"
    ]
  },
  {
    "id": 2,
    "slug": "audi-sq5-black-edition",
    "name": "Audi SQ5 Black Edition",
    "year": 2014,
    "km": 213000,
    "transmission": "Automatik",
    "fuel": "Dizel",
    "price": 26500,
    "sold": false,
    "headImage": "images/cars/audi-sq5-black-edition/6.jpg",
    "images": [
      "images/cars/audi-sq5-black-edition/1.jpg",
      "images/cars/audi-sq5-black-edition/2.jpg",
      "images/cars/audi-sq5-black-edition/3.jpg",
      "images/cars/audi-sq5-black-edition/4.jpg",
      "images/cars/audi-sq5-black-edition/5.jpg",
      "images/cars/audi-sq5-black-edition/7.jpg",
      "images/cars/audi-sq5-black-edition/8.jpg",
      "images/cars/audi-sq5-black-edition/9.jpg",
      "images/cars/audi-sq5-black-edition/10.jpg",
      "images/cars/audi-sq5-black-edition/11.jpg",
      "images/cars/audi-sq5-black-edition/12.jpg",
      "images/cars/audi-sq5-black-edition/13.jpg",
      "images/cars/audi-sq5-black-edition/14.jpg",
      "images/cars/audi-sq5-black-edition/15.jpg",
      "images/cars/audi-sq5-black-edition/16.jpg",
      "images/cars/audi-sq5-black-edition/17.jpg",
      "images/cars/audi-sq5-black-edition/18.jpg",
      "images/cars/audi-sq5-black-edition/19.jpg",
      "images/cars/audi-sq5-black-edition/20.jpg"
    ],
    "description": "Auto u odličnom stanju, izuzetno očuvan. Najveći stepen opreme — Black Edition paket. Original 20\" felne. Odrađeni svi servisi, kompletan servis trapova. Registrovan do 3/2027. Servisna istorija dostupna, pisana garancija na ispravnost dijelova automobila i servise.",
    "specs": {
      "engine": "3.0 V6 BiTDI",
      "power": "313 KS / 230 kW",
      "displacement": "2967 ccm",
      "drive": "Quattro (AWD)",
      "body": "SUV",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "5 modova vožnje",
      "Dupli panorama krov",
      "F1 šaltanje na volanu",
      "Alcantara/koža električna sjedišta",
      "Grijanje sjedišta i stakala",
      "AC digitalna klima",
      "Offroad mode vožnje",
      "ACC, praćenje traka, samokočenje",
      "Rikverc kamera, parking senzori",
      "Automatska svjetla, svjetla za maglu",
      "Senzori za svjetla i kišu",
      "Električni gepek",
      "Start/stop sistem",
      "Navigacija / multimedija"
    ]
  },
  {
    "id": 3,
    "slug": "ford-fiesta-titanium",
    "name": "Ford Fiesta Titanium",
    "year": 2013,
    "km": 224000,
    "transmission": "Manuelni",
    "fuel": "Dizel",
    "price": 5900,
    "sold": false,
    "headImage": "images/cars/ford-fiesta-titanium/1.jpg",
    "images": [
      "images/cars/ford-fiesta-titanium/2.jpg",
      "images/cars/ford-fiesta-titanium/3.jpg",
      "images/cars/ford-fiesta-titanium/4.jpg",
      "images/cars/ford-fiesta-titanium/5.jpg",
      "images/cars/ford-fiesta-titanium/6.jpg",
      "images/cars/ford-fiesta-titanium/7.jpg",
      "images/cars/ford-fiesta-titanium/8.jpg",
      "images/cars/ford-fiesta-titanium/9.jpg",
      "images/cars/ford-fiesta-titanium/10.jpg",
      "images/cars/ford-fiesta-titanium/11.jpg",
      "images/cars/ford-fiesta-titanium/12.jpg",
      "images/cars/ford-fiesta-titanium/13.jpg",
      "images/cars/ford-fiesta-titanium/14.jpg",
      "images/cars/ford-fiesta-titanium/15.jpg",
      "images/cars/ford-fiesta-titanium/16.jpg"
    ],
    "description": "Auto u odličnom stanju, najveći stepen opreme Titanium. Urađen mali servis, nove gume, 2 ključa. Ocarinjen, na ime kupca.",
    "specs": {
      "engine": "1.6 TDCi",
      "power": "95 KS / 70 kW",
      "displacement": "1560 ccm",
      "drive": "Prednji (FWD)",
      "body": "Hatchback",
      "color": "—",
      "doors": 5,
      "seats": 5
    },
    "features": [
      "Parking senzori",
      "Komande na volanu",
      "Isofix sjedišta",
      "AC digitalna klima",
      "Navigacija / multimedija",
      "Keyless off",
      "Start/stop sistem",
      "Automatska svjetla",
      "Senzori za svjetla i kišu",
      "Aluminijske felne",
      "Ambient light",
      "Sva 4 električna podizača",
      "Tempomat"
    ]
  }
];
